language: bash
sudo: required
dist: xenial
cache:
  directories:
    - /home/travis/build/libretro/Lakka-LibreELEC/sources
    - /home/travis/build/libretro/Lakka-LibreELEC/build.Lakka-Generic.x86_64-2.1-devel
env:
  - MAKEFLAGS="-j2" DISTRO=Lakka PROJECT=Generic ARCH=x86_64
before_install:
  - sudo rm /var/lib/dpkg/lock
  - sudo apt-get -qq update
install:
  - sudo apt-get install -y wget bash bc gcc sed patch patchutils tar bzip2 gzip perl gawk gperf zip unzip diffutils texinfo lzop libc6-dev libncurses5-dev g++ xfonts-utils xfonts-utils xfonts-utils xsltproc libjson-perl
script:
  - make image || true
