language: bash
sudo: required
dist: xenial
cache:
  directories:
    - sources
    - build.Lakka-*
env:
  - DISTRO=Lakka PROJECT=Generic ARCH=x86_64
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get install -y wget bash bc gcc sed patch patchutils tar bzip2 gzip perl gawk gperf zip unzip diffutils texinfo lzop libc6-dev libncurses5-dev g++ xfonts-utils xfonts-utils xfonts-utils xsltproc
script:
  - make image
